status = [
    "test (ubuntu-latest, stable)",
    "test (ubuntu-latest, nightly)",
    "test (macos-latest, stable)",
    "test (macos-latest, nightly)",
    "test (windows-latest, stable)",
    "test (windows-latest, nightly)",
    "style (clippy)",
    "style (rustfmt)",
]
delete_merged_branches = true
