# Rustfmt configuration
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

version = "Two" # https://github.com/rust-lang/rustfmt/issues/3383
use_small_heuristics = "Max"
merge_imports = true # https://github.com/rust-lang/rustfmt/issues/3362
format_code_in_doc_comments = true # https://github.com/rust-lang/rustfmt/issues/3348

# Set the default settings again to always apply the proper formatting without
# being affected by the editor settings.
# Refs: https://github.com/rust-lang/rls/issues/501#issuecomment-333717736
edition = "2018"
tab_spaces = 4
