language: rust
sudo: false
cache: cargo

matrix:
  fast_finish: true

  include:
    - rust: nightly

before_script:
  - set -o errexit

script:
  - cargo test
  - cargo test --release

notifications:
  email:
    on_success: never
