[package]
name = "replace-await"
version = "0.1.0"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
repository = "https://github.com/taiki-e/replace-await"
publish = false

[workspace]

[target.'cfg(windows)'.dependencies]
wild = "2.0.1"
