parameters:
  cmd: test

jobs:
- job: ${{ parameters.name }}
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-16.04
      ${{ if parameters.cross }}:
        MacOS:
          vmImage: macOS-10.13
        Windows:
          vmImage: vs2017-win2016
  pool:
    vmImage: $(vmImage)

  steps:
    - template: azure-install-rust.yml
      parameters:
        toolchain: ${{ parameters.toolchain }}

    - script: cargo ${{ parameters.cmd }}
      displayName: cargo ${{ parameters.cmd }}
