name: ci

on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying
  schedule:
    - cron: 00 01 * * 00 # Weekly

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: -Dwarnings
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        rust:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@master
      - name: Install Rust (rustup)
        if: matrix.os != 'macos-latest'
        run: |
          rustup self update # TODO: when default rustup is bumped to 1.20+, remove this.
          rustup set profile minimal
          rustup update ${{ matrix.rust }} --no-self-update && rustup default ${{ matrix.rust }}
      - name: Install Rust (macos)
        if: matrix.os == 'macos-latest'
        run: |
          curl https://sh.rustup.rs | sh -s -- -y --default-toolchain ${{ matrix.rust }} --profile minimal
          echo "##[add-path]$HOME/.cargo/bin"
      - name: cargo test
        run: |
          cargo test

  style:
    name: style
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings
    strategy:
      fail-fast: false
      matrix:
        component:
          - clippy
          - rustfmt
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: |
          rustup self update # TODO: when default rustup is bumped to 1.20+, remove this.
          rustup set profile minimal
          rustup update nightly && rustup default nightly
      - name: Install component
        run: |
          if ! rustup component add ${{ matrix.component }}; then
            # If the component is unavailable on the latest nightly,
            # use the latest toolchain with the component available.
            # Refs: https://github.com/rust-lang/rustup-components-history#the-web-part
            component=${{ matrix.component }}
            target=`curl https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/$component`
            echo "'$component' is unavailable on the toolchain 'nightly', use the toolchain 'nightly-$target' instead"
            rustup toolchain install nightly-$target
            rustup default nightly-$target
            rustup component add $component
          fi
      - name: cargo clippy
        if: matrix.component == 'clippy'
        run: |
          cargo clippy --all --all-features
      - name: cargo fmt -- --check
        if: matrix.component == 'rustfmt'
        run: |
          cargo fmt --all -- --check
