name: ci

on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying
  schedule:
    - cron: '00 01 * * *'

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        shell: bash
        run: |
          . ./ci/install-rust.sh ${{ matrix.rust }}
      - name: cargo test
        run: |
          cargo test

  style:
    name: style
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component:
          - clippy
          - rustfmt
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        shell: bash
        run: |
          . ./ci/install-rust.sh
      - name: Install component
        shell: bash
        run: |
          . ./ci/install-component.sh ${{ matrix.component }}
      - name: cargo clippy
        if: matrix.component == 'clippy'
        run: |
          cargo clippy --all --all-features --all-targets
      - name: cargo fmt -- --check
        if: matrix.component == 'rustfmt'
        run: |
          cargo fmt --all -- --check
